//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> SanPham { get; set; }
        public string HoTenKH { get; set; }
        public string SDT { get; set; }
        public int ID { get; set; }
    
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
