//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class QUANLYWEBEntities : DbContext
    {
        public QUANLYWEBEntities()
            : base("name=QUANLYWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual List<SANPHAM> danhsachbanchay(int so) {
            var sxBanchay = SANPHAMs.OrderByDescending(p => p.LuotMua);
            var ds = sxBanchay.Take(so).ToList();
            return ds;
        }
        public virtual List<SANPHAM> danhsachyeuthich(int so)
        {
            var sxBanchay = SANPHAMs.OrderByDescending(p => p.LuotThich);
            var ds = sxBanchay.Take(so).ToList();
            return ds;
        }
        public virtual DbSet<DATHANG> DATHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    }
}
