//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSchange_tracking_history
    {
        public string internal_table_name { get; set; }
        public string table_name { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public long rows_cleaned_up { get; set; }
        public long cleanup_version { get; set; }
        public string comments { get; set; }
    }
}
