//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.DATHANGs = new HashSet<DATHANG>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> LoaiSanPham { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotMua { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string MoTaNgan { get; set; }
        public string HinhCT1 { get; set; }
        public string HinhCT2 { get; set; }
        public string MoTaCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM1 { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}
